//! In-QEMU test kernel for librheo Phase B (docs/LIBRHEO.md): the **mini-DuckDB
//! scan**. A columnar dataset is read off the *live virtio-blk disk* (attached
//! by the harness with `-drive`, generated by xtask), served to a librheo cell
//! through a single-file `FileOps`, and the cell runs the whole Phase B surface:
//! typed memory grants (commit/decommit/seal), async I/O over the OP_* queue
//! opcodes (open/fstat/read/write), a batched async read into a grant, and a
//! zero-copy mmap columnar scan fanned across strands. The demo exits `0x42`
//! only if the exact aggregate is computed, so the exit code is the proof.
//!
//! Wiring mirrors `librhearun` (queue pair + minted cap + `set_queue_info`) and
//! `blockfs` (virtio-blk discovery). The dataset is raw (no filesystem): the
//! kernel reads the whole disk into RAM, and `blob_fs` serves `/data.col` from
//! it - so the async I/O and mmap paths both reach the live-disk bytes.

#![no_std]
#![no_main]

extern crate alloc;

use core::mem::MaybeUninit;
use core::ptr::addr_of_mut;

use kernel::abi::Stat;
use kernel::capability::{BUDGET_UNLIMITED, CapTable, ObjectKind, ObjectTable, READ, WRITE};
use kernel::hw::block::BlockDevice;
use kernel::hw::virtio_blk;
use kernel::mm::AddressSpace;
use kernel::queue::QueuePair;
use kernel::svc::{self, FileOps};
use kernel::user::{self, Outcome};
use kernel::{arch, load, println};

#[cfg(target_arch = "x86_64")]
static DEMO: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../target/x86_64-unknown-none/release/librheo-data"
));
#[cfg(target_arch = "aarch64")]
static DEMO: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../target/aarch64-unknown-none-softfloat/release/librheo-data"
));
#[cfg(target_arch = "riscv64")]
static DEMO: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../target/riscv64gc-unknown-none-elf/release/librheo-data"
));

const EXPECTED_EXIT: u64 = 0x42;

// Kernel heap (holds the whole-disk copy leaked as the dataset blob).
#[global_allocator]
static HEAP: runtime::Heap = runtime::Heap::empty();
static mut HEAP_MEM: [u8; 4 * 1024 * 1024] = [0; 4 * 1024 * 1024];

// -------- the single-file dataset "filesystem" served from the live disk -----
// A minimal FileOps over one in-RAM blob (the disk bytes). `/data.col` is the
// only file; reads are positional (lseek sets the cursor, read copies from it);
// fstat reports the dataset's meaningful size; fd 1/2 write to the console.
static mut BLOB: &[u8] = &[];
static mut BLOB_SIZE: usize = 0;
static mut CURSOR: u64 = 0;
const DATA_FD: u64 = 3;

fn blob() -> &'static [u8] {
    unsafe { *addr_of_mut!(BLOB) }
}

fn bf_open(path_va: u64, path_len: u64, _flags: u64) -> i64 {
    let bytes = unsafe { core::slice::from_raw_parts(path_va as *const u8, path_len as usize) };
    if bytes == b"/data.col" {
        unsafe {
            CURSOR = 0;
        }
        DATA_FD as i64
    } else {
        -2 // ENOENT
    }
}
fn bf_close(_fd: u64) -> i64 {
    0
}
fn bf_lseek(_fd: u64, off: i64, _whence: u64) -> i64 {
    // SEEK_SET only (the kernel/librheo read path is positional).
    unsafe {
        CURSOR = off as u64;
    }
    off
}
fn bf_read(fd: u64, buf_va: u64, len: u64) -> i64 {
    if fd != DATA_FD {
        return -9; // EBADF
    }
    let b = blob();
    let cur = unsafe { CURSOR } as usize;
    let n = (len as usize).min(b.len().saturating_sub(cur));
    let dst = unsafe { core::slice::from_raw_parts_mut(buf_va as *mut u8, n) };
    dst.copy_from_slice(&b[cur..cur + n]);
    unsafe {
        CURSOR += n as u64;
    }
    n as i64
}
fn bf_write(fd: u64, buf_va: u64, len: u64) -> i64 {
    if fd == 1 || fd == 2 {
        let buf = unsafe { core::slice::from_raw_parts(buf_va as *const u8, len as usize) };
        for &b in buf {
            arch::serial_write_byte(b);
        }
        len as i64
    } else {
        -9
    }
}
fn bf_stat(_p: u64, _l: u64, _s: u64) -> i64 {
    -38 // ENOSYS (unused)
}
fn bf_fstat(fd: u64, statbuf_va: u64) -> i64 {
    if fd != DATA_FD {
        return -9;
    }
    let st = Stat {
        size: unsafe { BLOB_SIZE } as u64,
        kind: 0,
    };
    unsafe {
        (statbuf_va as *mut Stat).write(st);
    }
    0
}
fn bf_getdents(_p: u64, _l: u64, _b: u64, _bl: u64) -> i64 {
    -38
}

static mut OBJECTS: ObjectTable = ObjectTable::new();
static mut CAPS: CapTable = CapTable::new();
static mut QP: MaybeUninit<QueuePair> = MaybeUninit::uninit();

#[repr(align(16))]
struct KStack([u8; 64 * 1024]);
static mut KSTACK: KStack = KStack([0; 64 * 1024]);

fn rd_u32(b: &[u8], o: usize) -> u32 {
    u32::from_le_bytes([b[o], b[o + 1], b[o + 2], b[o + 3]])
}

#[unsafe(no_mangle)]
extern "C" fn kernel_main() -> ! {
    kernel::boot::init();
    println!("librheodata: start on {}", arch::NAME);

    // SAFETY: once, before any allocation; HEAP_MEM is a unique static.
    unsafe {
        HEAP.init(addr_of_mut!(HEAP_MEM) as usize, 4 * 1024 * 1024);
    }

    // Read the columnar dataset off the live virtio-blk disk.
    let dev = match virtio_blk::probe() {
        Some(d) => d,
        None => {
            println!("librheodata: no virtio-blk device attached - skipping");
            println!("librheodata: PASS");
            arch::exit(arch::ExitCode::Success)
        }
    };
    let sectors = dev.capacity_sectors();
    let bytes = sectors as usize * 512;
    let mut disk = alloc::vec![0u8; bytes];
    dev.read(0, &mut disk).expect("read disk");
    let img: &'static [u8] = alloc::vec::Vec::leak(disk);

    // Validate the header and compute the dataset's meaningful size.
    assert!(img.len() >= 16, "disk too small");
    assert!(rd_u32(img, 0) == 0x314C_4F43, "bad dataset magic");
    let nrows = rd_u32(img, 4) as usize;
    let ncols = rd_u32(img, 8) as usize;
    let size = 16 + nrows * ncols * 4;
    assert!(size <= img.len(), "dataset larger than disk");
    println!("librheodata: dataset {nrows} rows x {ncols} cols ({size} bytes) off live disk");

    // SAFETY: single-threaded init, before the cell runs.
    unsafe {
        *addr_of_mut!(BLOB) = &img[..size];
        BLOB_SIZE = size;
    }

    svc::init();
    svc::set_file_ops(FileOps {
        open: bf_open,
        close: bf_close,
        read: bf_read,
        write: bf_write,
        lseek: bf_lseek,
        stat: bf_stat,
        fstat: bf_fstat,
        getdents: bf_getdents,
    });

    let mut aspace = AddressSpace::new(1);
    let entry = load::load_elf(DEMO, &mut aspace).expect("load librheo-data ELF");
    let stack_top = load::map_stack(&mut aspace);
    let qp = load::map_queue(&mut aspace);

    // SAFETY: single-threaded init; the statics outlive the run.
    let outcome = unsafe {
        let objects = &mut *addr_of_mut!(OBJECTS);
        let caps = &mut *addr_of_mut!(CAPS);
        let object = objects.create(ObjectKind::QueuePair).unwrap();
        let cap = caps
            .mint(objects, object, READ | WRITE, BUDGET_UNLIMITED)
            .unwrap();
        let cap_id = cap.raw_low32();

        (*addr_of_mut!(QP)).write(qp);
        let qp_ptr = (*addr_of_mut!(QP)).as_ptr();

        let kernel_sp = core::ptr::addr_of!(KSTACK.0) as usize + 64 * 1024;
        let mut frame = arch::trapframe_new(entry, stack_top, 0, kernel_sp);
        user::reset();
        user::install(0, &aspace, caps, objects, qp_ptr, addr_of_mut!(frame));
        user::set_queue_info(0, load::USER_QUEUE_VA as u64, cap_id);
        user::run(0).1
    };

    match outcome {
        Outcome::Exited(code) => {
            assert!(
                code == EXPECTED_EXIT,
                "librheo-data exited {code:#x}, expected {EXPECTED_EXIT:#x}"
            );
            println!(
                "librheodata: mini-DuckDB scan (grants+async-io+zero-copy), exit {code:#x} OK"
            );
        }
        Outcome::Faulted(addr) => panic!("librheo-data faulted at {addr:#x}"),
    }

    println!("librheodata: PASS");
    arch::exit(arch::ExitCode::Success)
}
